// Committee Member Action Types
export const FETCH_COMMITTEE_MEMBERS_REQUEST = 'FETCH_COMMITTEE_MEMBERS_REQUEST';
export const FETCH_COMMITTEE_MEMBERS_SUCCESS = 'FETCH_COMMITTEE_MEMBERS_SUCCESS';
export const FETCH_COMMITTEE_MEMBERS_FAILURE = 'FETCH_COMMITTEE_MEMBERS_FAILURE';

export const FETCH_COMMITTEE_MEMBER_BY_ID_REQUEST = 'FETCH_COMMITTEE_MEMBER_BY_ID_REQUEST';
export const FETCH_COMMITTEE_MEMBER_BY_ID_SUCCESS = 'FETCH_COMMITTEE_MEMBER_BY_ID_SUCCESS';
export const FETCH_COMMITTEE_MEMBER_BY_ID_FAILURE = 'FETCH_COMMITTEE_MEMBER_BY_ID_FAILURE';

export const CREATE_COMMITTEE_MEMBER_REQUEST = 'CREATE_COMMITTEE_MEMBER_REQUEST';
export const CREATE_COMMITTEE_MEMBER_SUCCESS = 'CREATE_COMMITTEE_MEMBER_SUCCESS';
export const CREATE_COMMITTEE_MEMBER_FAILURE = 'CREATE_COMMITTEE_MEMBER_FAILURE';

export const UPDATE_COMMITTEE_MEMBER_REQUEST = 'UPDATE_COMMITTEE_MEMBER_REQUEST';
export const UPDATE_COMMITTEE_MEMBER_SUCCESS = 'UPDATE_COMMITTEE_MEMBER_SUCCESS';
export const UPDATE_COMMITTEE_MEMBER_FAILURE = 'UPDATE_COMMITTEE_MEMBER_FAILURE';

export const DELETE_COMMITTEE_MEMBER_REQUEST = 'DELETE_COMMITTEE_MEMBER_REQUEST';
export const DELETE_COMMITTEE_MEMBER_SUCCESS = 'DELETE_COMMITTEE_MEMBER_SUCCESS';
export const DELETE_COMMITTEE_MEMBER_FAILURE = 'DELETE_COMMITTEE_MEMBER_FAILURE';

// Donor Action Types
export const FETCH_DONORS_REQUEST = 'FETCH_DONORS_REQUEST';
export const FETCH_DONORS_SUCCESS = 'FETCH_DONORS_SUCCESS';
export const FETCH_DONORS_FAILURE = 'FETCH_DONORS_FAILURE';

export const FETCH_DONOR_BY_ID_REQUEST = 'FETCH_DONOR_BY_ID_REQUEST';
export const FETCH_DONOR_BY_ID_SUCCESS = 'FETCH_DONOR_BY_ID_SUCCESS';
export const FETCH_DONOR_BY_ID_FAILURE = 'FETCH_DONOR_BY_ID_FAILURE';

export const CREATE_DONOR_REQUEST = 'CREATE_DONOR_REQUEST';
export const CREATE_DONOR_SUCCESS = 'CREATE_DONOR_SUCCESS';
export const CREATE_DONOR_FAILURE = 'CREATE_DONOR_FAILURE';

export const UPDATE_DONOR_REQUEST = 'UPDATE_DONOR_REQUEST';
export const UPDATE_DONOR_SUCCESS = 'UPDATE_DONOR_SUCCESS';
export const UPDATE_DONOR_FAILURE = 'UPDATE_DONOR_FAILURE';

export const DELETE_DONOR_REQUEST = 'DELETE_DONOR_REQUEST';
export const DELETE_DONOR_SUCCESS = 'DELETE_DONOR_SUCCESS';
export const DELETE_DONOR_FAILURE = 'DELETE_DONOR_FAILURE';

// Blood Donor Action Types
export const FETCH_BLOOD_DONORS_REQUEST = 'FETCH_BLOOD_DONORS_REQUEST';
export const FETCH_BLOOD_DONORS_SUCCESS = 'FETCH_BLOOD_DONORS_SUCCESS';
export const FETCH_BLOOD_DONORS_FAILURE = 'FETCH_BLOOD_DONORS_FAILURE';

export const FETCH_BLOOD_DONOR_BY_ID_REQUEST = 'FETCH_BLOOD_DONOR_BY_ID_REQUEST';
export const FETCH_BLOOD_DONOR_BY_ID_SUCCESS = 'FETCH_BLOOD_DONOR_BY_ID_SUCCESS';
export const FETCH_BLOOD_DONOR_BY_ID_FAILURE = 'FETCH_BLOOD_DONOR_BY_ID_FAILURE';

export const CREATE_BLOOD_DONOR_REQUEST = 'CREATE_BLOOD_DONOR_REQUEST';
export const CREATE_BLOOD_DONOR_SUCCESS = 'CREATE_BLOOD_DONOR_SUCCESS';
export const CREATE_BLOOD_DONOR_FAILURE = 'CREATE_BLOOD_DONOR_FAILURE';

export const UPDATE_BLOOD_DONOR_REQUEST = 'UPDATE_BLOOD_DONOR_REQUEST';
export const UPDATE_BLOOD_DONOR_SUCCESS = 'UPDATE_BLOOD_DONOR_SUCCESS';
export const UPDATE_BLOOD_DONOR_FAILURE = 'UPDATE_BLOOD_DONOR_FAILURE';

export const DELETE_BLOOD_DONOR_REQUEST = 'DELETE_BLOOD_DONOR_REQUEST';
export const DELETE_BLOOD_DONOR_SUCCESS = 'DELETE_BLOOD_DONOR_SUCCESS';
export const DELETE_BLOOD_DONOR_FAILURE = 'DELETE_BLOOD_DONOR_FAILURE';

// Volunteer Action Types
export const FETCH_VOLUNTEERS_REQUEST = 'FETCH_VOLUNTEERS_REQUEST';
export const FETCH_VOLUNTEERS_SUCCESS = 'FETCH_VOLUNTEERS_SUCCESS';
export const FETCH_VOLUNTEERS_FAILURE = 'FETCH_VOLUNTEERS_FAILURE';

export const FETCH_VOLUNTEER_BY_ID_REQUEST = 'FETCH_VOLUNTEER_BY_ID_REQUEST';
export const FETCH_VOLUNTEER_BY_ID_SUCCESS = 'FETCH_VOLUNTEER_BY_ID_SUCCESS';
export const FETCH_VOLUNTEER_BY_ID_FAILURE = 'FETCH_VOLUNTEER_BY_ID_FAILURE';

export const CREATE_VOLUNTEER_REQUEST = 'CREATE_VOLUNTEER_REQUEST';
export const CREATE_VOLUNTEER_SUCCESS = 'CREATE_VOLUNTEER_SUCCESS';
export const CREATE_VOLUNTEER_FAILURE = 'CREATE_VOLUNTEER_FAILURE';

export const UPDATE_VOLUNTEER_REQUEST = 'UPDATE_VOLUNTEER_REQUEST';
export const UPDATE_VOLUNTEER_SUCCESS = 'UPDATE_VOLUNTEER_SUCCESS';
export const UPDATE_VOLUNTEER_FAILURE = 'UPDATE_VOLUNTEER_FAILURE';

export const DELETE_VOLUNTEER_REQUEST = 'DELETE_VOLUNTEER_REQUEST';
export const DELETE_VOLUNTEER_SUCCESS = 'DELETE_VOLUNTEER_SUCCESS';
export const DELETE_VOLUNTEER_FAILURE = 'DELETE_VOLUNTEER_FAILURE';

// Gallery Image Action Types
export const FETCH_GALLERY_IMAGES_REQUEST = 'FETCH_GALLERY_IMAGES_REQUEST';
export const FETCH_GALLERY_IMAGES_SUCCESS = 'FETCH_GALLERY_IMAGES_SUCCESS';
export const FETCH_GALLERY_IMAGES_FAILURE = 'FETCH_GALLERY_IMAGES_FAILURE';

export const FETCH_GALLERY_IMAGE_BY_ID_REQUEST = 'FETCH_GALLERY_IMAGE_BY_ID_REQUEST';
export const FETCH_GALLERY_IMAGE_BY_ID_SUCCESS = 'FETCH_GALLERY_IMAGE_BY_ID_SUCCESS';
export const FETCH_GALLERY_IMAGE_BY_ID_FAILURE = 'FETCH_GALLERY_IMAGE_BY_ID_FAILURE';

export const CREATE_GALLERY_IMAGE_REQUEST = 'CREATE_GALLERY_IMAGE_REQUEST';
export const CREATE_GALLERY_IMAGE_SUCCESS = 'CREATE_GALLERY_IMAGE_SUCCESS';
export const CREATE_GALLERY_IMAGE_FAILURE = 'CREATE_GALLERY_IMAGE_FAILURE';

export const UPDATE_GALLERY_IMAGE_REQUEST = 'UPDATE_GALLERY_IMAGE_REQUEST';
export const UPDATE_GALLERY_IMAGE_SUCCESS = 'UPDATE_GALLERY_IMAGE_SUCCESS';
export const UPDATE_GALLERY_IMAGE_FAILURE = 'UPDATE_GALLERY_IMAGE_FAILURE';

export const DELETE_GALLERY_IMAGE_REQUEST = 'DELETE_GALLERY_IMAGE_REQUEST';
export const DELETE_GALLERY_IMAGE_SUCCESS = 'DELETE_GALLERY_IMAGE_SUCCESS';
export const DELETE_GALLERY_IMAGE_FAILURE = 'DELETE_GALLERY_IMAGE_FAILURE';
